# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dusanmilosevic
app: bank
service: reporting
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  onTransactionPublished:
    handler: api/onTransactionPublished.handler
    events:
      - eventBridge:
          pattern:
            source:
              - accountsLambda.apply.transaction
            detail-type:
              - transaction
  getMonthlyStatement:
    handler: api/getMonthlyStatement.handler
    events:
      - httpApi:
          path: /reports/{accountId}
          method: get
