# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dusanmilosevic
app: bank
service: reporting
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x

functions:
  onTransactionPublished:
    handler: onTransactionPublished/handler.onTransactionPublished
    events:
      - eventBridge:
        pattern:
          source:
            - aws.lambda
          detail-type:
            - AWS API Call via CloudTrail
          detail:
            eventSource:
              - lambda.amazonaws.com
