# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dusanmilosevic
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: account
# "service" is the name of this project. This will also be added to your AWS resource names.
service: account

provider:
  name: aws
  runtime: nodejs20.x

functions:
  account:
    handler: handler.account
    events:
      - httpApi:
          path: /
          method: get
